INSERT INTO products (name, description, category_id, price, quantity, image_url, created_at, updated_at) VALUES
('Мужская футболка "Классика"', 'Удобная футболка из 100% хлопка, идеальна для повседневной носки.', 1, 19.99, 100, 'https://storage.yandexcloud.net/kingsman-shop/tshirt_man.jpg', NOW(), NOW()),
('Женское платье "Летний бриз"', 'Легкое летнее платье из дышащей ткани, прекрасно подходит для жарких дней.', 2, 39.99, 75, 'https://storage.yandexcloud.net/kingsman-shop/dress_w.jpg', NOW(), NOW()),
('Унисекс худи "Комфорт"', 'Мягкое и теплое худи, подходит для мужчин и женщин. Отлично для прохладной погоды.', 3, 49.99, 50, 'https://storage.yandexcloud.net/kingsman-shop/hoodie_unisex.jpg', NOW(), NOW()),
('Джинсы "Слим Фит"', 'Стильные джинсы с зауженным кроем, выполненные из высококачественного денима.', 1, 59.99, 80, 'https://storage.yandexcloud.net/kingsman-shop/jeans.jpg', NOW(), NOW()),
('Кроссовки "Городской стиль"', 'Легкие и удобные кроссовки для активного образа жизни.', 4, 79.99, 60, 'https://storage.yandexcloud.net/kingsman-shop/sneakers.jpg', NOW(), NOW()),
('Демисезонная куртка', 'Практичная куртка для весны и осени, защищает от ветра и дождя.', 1, 89.99, 40, 'https://storage.yandexcloud.net/kingsman-shop/jacket.jpg', NOW(), NOW()),
('Женская юбка "Миди"', 'Элегантная юбка длины миди, идеально подходит для офиса и вечерних выходов.', 2, 34.99, 70, 'https://storage.yandexcloud.net/kingsman-shop/skirt_w.jpg', NOW(), NOW()),
('Мужская рубашка "Кэжуал"', 'Повседневная рубашка из мягкой ткани, удобна и стильна.', 1, 45.99, 90, 'https://storage.yandexcloud.net/kingsman-shop/shirt_man.jpg', NOW(), NOW()),
('Спортивные шорты', 'Легкие шорты для занятий спортом и активного отдыха.', 3, 24.99, 110, 'https://storage.yandexcloud.net/kingsman-shop/shorts_unisex.jpg', NOW(), NOW()),
('Вязаный свитер "Уют"', 'Теплый свитер крупной вязки, согреет в холодную погоду.', 1, 69.99, 30, 'https://storage.yandexcloud.net/kingsman-shop/sweater.jpg', NOW(), NOW()),
('Женские леггинсы', 'Эластичные леггинсы для йоги и фитнеса.', 2, 29.99, 120, 'https://storage.yandexcloud.net/kingsman-shop/leggings_w.jpg', NOW(), NOW()),
('Классические брюки', 'Строгие брюки прямого кроя, подходят для делового стиля.', 1, 65.99, 65, 'https://storage.yandexcloud.net/kingsman-shop/trousers_man.jpg', NOW(), NOW()),
('Бомбер "Урбан"', 'Стильный бомбер для создания модного городского образа.', 1, 95.99, 35, 'https://storage.yandexcloud.net/kingsman-shop/bomber_jacket.jpg', NOW(), NOW()),
('Топ "Кроп"', 'Короткий топ, идеально сочетается с юбками и джинсами с высокой талией.', 2, 14.99, 150, 'https://storage.yandexcloud.net/kingsman-shop/crop_top_w.jpg', NOW(), NOW()),
('Пальто "Оверсайз"', 'Модное пальто свободного кроя, подходит для создания многослойных образов.', 2, 120.00, 25, 'https://storage.yandexcloud.net/kingsman-shop/oversize_coat.jpg', NOW(), NOW()),
('Поло "Спорт Шик"', 'Классическая рубашка поло для спортивного или повседневного стиля.', 1, 35.99, 95, 'https://storage.yandexcloud.net/kingsman-shop/polo_shirt_man.jpg', NOW(), NOW()),
('Комбинезон "Элегант"', 'Изысканный комбинезон для особых случаев.', 2, 75.99, 45, 'https://storage.yandexcloud.net/kingsman-shop/jumpsuit_w.jpg', NOW(), NOW()),
('Рубашка с длинным рукавом', 'Универсальная рубашка для любого сезона.', 1, 49.99, 85, 'https://storage.yandexcloud.net/kingsman-shop/long_sleeve_shirt.jpg', NOW(), NOW()),
('Брюки чинос женские', 'Удобные и стильные брюки чинос для женщин.', 2, 55.99, 70, 'https://storage.yandexcloud.net/kingsman-shop/chinos_w.jpg', NOW(), NOW()),
('Пуховик "Зимний"', 'Теплый пуховик, незаменим в холодную зимнюю погоду.', 1, 150.00, 20, 'https://storage.yandexcloud.net/kingsman-shop/winter_jacket.jpg', NOW(), NOW()),
('Свитшот "Базовый"', 'Мягкий свитшот без капюшона, идеален для домашнего уюта.', 3, 30.00, 100, 'https://storage.yandexcloud.net/kingsman-shop/sweatshirt.jpg', NOW(), NOW()),
('Плащ "Тренч"', 'Классический тренч, добавляет образу элегантности.', 2, 110.00, 30, 'https://storage.yandexcloud.net/kingsman-shop/trench_coat_w.jpg', NOW(), NOW()),
('Толстовка с принтом', 'Модная толстовка с уникальным принтом.', 3, 40.00, 60, 'https://storage.yandexcloud.net/kingsman-shop/printed_hoodie.jpg', NOW(), NOW()),
('Шелковая блузка', 'Легкая и воздушная блузка из натурального шелка.', 2, 60.00, 50, 'https://storage.yandexcloud.net/kingsman-shop/silk_blouse_w.jpg', NOW(), NOW()),
('Кожаная куртка', 'Стильная кожаная куртка, классика мужского гардероба.', 1, 180.00, 15, 'https://storage.yandexcloud.net/kingsman-shop/leather_jacket_man.jpg', NOW(), NOW()),
('Купальник "Бикини"', 'Яркий купальник для пляжного отдыха.', 2, 25.00, 80, 'https://storage.yandexcloud.net/kingsman-shop/bikini_w.jpg', NOW(), NOW()),
('Спортивный костюм', 'Удобный спортивный костюм для тренировок и отдыха.', 3, 70.00, 40, 'https://storage.yandexcloud.net/kingsman-shop/sport_suit_unisex.jpg', NOW(), NOW()),
('Вечернее платье', 'Изысканное вечернее платье для торжественных мероприятий.', 2, 99.00, 20, 'https://storage.yandexcloud.net/kingsman-shop/evening_dress_w.jpg', NOW(), NOW()),
('Шапка-бини', 'Теплая шапка-бини для прохладной погоды.', 3, 15.00, 200, 'https://storage.yandexcloud.net/kingsman-shop/beanie.jpg', NOW(), NOW()),
('Классический пиджак', 'Элегантный пиджак для делового или праздничного образа.', 1, 100.00, 30, 'https://storage.yandexcloud.net/kingsman-shop/blazer_man.jpg', NOW(), NOW());